export const GUEST_LECTURER_CAMPAIGN_KEY: string;
export const GUEST_LECTURER_CARD_ID: string;
export const GUEST_LECTURER_PUBLIC_ROUTE: string;
export const GUEST_LECTURER_APP_ROUTE: string;
export const GUEST_LECTURER_CARD_MARK: string;
export const GUEST_LECTURER_CARD_LOGO_URL: string;
export const GUEST_LECTURER_CARD_TITLE: string;
export const GUEST_LECTURER_CARD_SUMMARY: string;
export const GUEST_LECTURER_PAGE_TITLE: string;
export const GUEST_LECTURER_PAGE_SUMMARY: string;
export const GUEST_LECTURER_CONFIRMATION_COPY: string;
export const GUEST_LECTURER_COURSE_OUTLINE_URL: string;
export const GUEST_LECTURER_TOPIC_FIELD_LABEL: string;
export const GUEST_LECTURER_TOPIC_FIELD_PLACEHOLDER: string;
export const GUEST_LECTURER_ORGANISATION: string;
export const GUEST_LECTURER_CAMPUS: string;
export const GUEST_LECTURER_BUILDING: string;
export const GUEST_LECTURER_LOCATION_LABEL: string;
export const GUEST_LECTURER_MAP_LINK: string;
export const GUEST_LECTURER_MAP_EMBED_SRC: string;
export const GUEST_LECTURER_TIMEZONE: string;
export const GUEST_LECTURER_CLASS_START_HOUR: number;
export const GUEST_LECTURER_CLASS_START_MINUTE: number;
export const GUEST_LECTURER_CLASS_END_HOUR: number;
export const GUEST_LECTURER_CLASS_END_MINUTE: number;
export const GUEST_LECTURER_TIME_LABEL: string;
export const GUEST_LECTURER_SEGMENT_LABEL: string;
export const GUEST_LECTURER_OFF_WEEK_NUMBER: number;
export const GUEST_LECTURER_WEEKS: Array<{
  weekNumber: number;
  label: string;
  date: string;
  theme: string;
  isOff: boolean;
}>;
export const GUEST_LECTURER_ACTIVE_WEEK_NUMBERS: number[];
export function getGuestLecturerWeek(weekNumber: number): {
  weekNumber: number;
  label: string;
  date: string;
  theme: string;
  isOff: boolean;
} | null;
